name: Build, test and publish image

on:
  push:
    branches:
      - master
      - dev-master
    paths:
      - .github/workflows/publish-image.yml
      - .github/matrix.json
      - 'docker/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Load JSON file
        id: load
        working-directory: ./.github
        run: echo "matrix=$(tr -d '\n' < matrix.json)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ vars.IMAGE_NAME }}
          tags: |
            type=raw,${{ matrix.version }},enable=${{ matrix.latest_dotnet }}
            type=raw,dotnet${{ matrix.dotnet_version }},enable=${{ matrix.latest }}
            ${{ matrix.version }}-dotnet${{ matrix.dotnet_version }}
          flavor: |
            latest=${{ matrix.latest && matrix.latest_dotnet }}
      -
        name: Set CACHE_IMAGE environment variable
        run: echo "CACHE_IMAGE=${{ vars.IMAGE_NAME }}:buildcache-${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
      -
        name: Set TEST_IMAGE environment variable
        run: echo "TEST_IMAGE=${{ vars.IMAGE_NAME }}:test-${{ steps.meta.outputs.version }}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build test image and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ./docker/root
          file: ./docker/Dockerfile
          build-args: |
            WEBONE_VERSION=${{ matrix.version }}
            DOTNET_VERSION=${{ matrix.dotnet_version }}
          tags: ${{ env.TEST_IMAGE }}
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          load: true
      -
        name: Executing tests
        working-directory: ./docker/tests
        run: |
          bash test_proxy.sh -v ./custom.conf:/opt/webone/webone.conf.d/100_custom.conf ${{ env.TEST_IMAGE }}
          bash test_proxy.sh -v ./custom.conf:/opt/webone/webone.conf.d/100_custom.conf -u 1001:1001 ${{ env.TEST_IMAGE }}
      -
        if: ${{ github.event_name == 'push' &&  github.ref_name == 'master' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        if: ${{ github.event_name == 'push' &&  github.ref_name == 'master' }}
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/root
          file: ./docker/Dockerfile
          build-args: |
            WEBONE_VERSION=${{ matrix.version }}
            DOTNET_VERSION=${{ matrix.dotnet_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
          push: true
