name: Build and publish images

on:
  push:
    branches:
      - master
      - dev-master
    paths:
      - .github/workflows/publish-image.yml
      - .github/matrix.json
      - 'docker/**'
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.load.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Load JSON file
        id: load
        working-directory: ./.github
        run: echo "matrix=$(tr -d '\n' < matrix.json)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.IMAGE_NAME }}
          tags: |
            type=raw,${{ matrix.version }},enable=${{ matrix.latestSDK }}
            ${{ matrix.version }}-dotnet-${{ matrix.sdk_version }}
          flavor: |
            latest=${{ matrix.latest }}
      -
        name: Setting environment variables
        run: |
          image="${{ vars.IMAGE_NAME }}"
          version="${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"
          cat << EOF >> $GITHUB_ENV
          CACHE_IMAGE=$image:buildcache-$version
          TEST_IMAGE=$image:test-$version
          EOF
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: ./docker/root
          file: ./docker/Dockerfile
          build-args: |
            WEBONE_VERSION=${{ matrix.version }}
            DOTNET_SDK_VERSION=${{ matrix.sdk_version }}
          tags: ${{ env.TEST_IMAGE }}
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          load: true
      -
        name: Executing tests
        working-directory: ./tests
        run: |
          bash test_proxy.sh -v ./custom.conf:/opt/webone/webone.conf.d/100_custom.conf ${{ env.TEST_IMAGE }}
          bash test_proxy.sh -v ./custom.conf:/opt/webone/webone.conf.d/100_custom.conf -u 1001:1001 ${{ env.TEST_IMAGE }}
      -
        name: Login to Docker Hub
        if: ${{ github.event_name == 'push' &&  github.ref_name == 'master' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        if: ${{ github.event_name == 'push' &&  github.ref_name == 'master' }}
        uses: docker/build-push-action@v6
        with:
          context: ./docker/root
          file: ./docker/Dockerfile
          build-args: |
            WEBONE_VERSION=${{ matrix.version }}
            DOTNET_SDK_VERSION=${{ matrix.sdk_version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max
          push: true
